'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ms' | 'en' | 'zh';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'ms',
  setLang: () => {},
  t: (key) => key,
});

export const translations: Record<Language, Record<string, string>> = {
  ms: {
    'nav.untuk_siapa': 'Untuk Siapa','nav.harga': 'Harga','nav.blog': 'Blog','nav.manual': 'Manual','nav.sokongan': 'Sokongan','nav.log_masuk': 'Log Masuk','nav.mula_sekarang': 'Mula Sekarang','nav.dashboard': 'Dashboard','nav.log_keluar': 'Log Keluar',
    'home.badge': 'Sistem Rujukan Rasmi ePerolehan Malaysia','home.hero_title': 'Jawapan Tepat ePerolehan.','home.hero_title2': 'Terus dari Dokumen Rasmi.','home.hero_sub': 'Sistem AI pertama Malaysia yang menjawab soalan ePerolehan berdasarkan 59 dokumen rasmi, 7,375 muka surat — bukan agakan.','home.cta_primary': 'Cuba Percuma Sekarang','home.cta_secondary': 'Lihat Pelan & Harga','home.free_note': '5 soalan percuma setiap hari · Tiada kad kredit diperlukan','home.stats_docs': 'Dokumen Rasmi','home.stats_pages': 'Muka Surat','home.stats_chunks': 'Potongan Data','home.stats_accuracy': 'Ketepatan',
    'pricing.badge': 'Harga Telus','pricing.title': 'Pilihan yang sesuai untuk setiap keperluan.','pricing.sub': 'Mulakan dengan PERCUMA dengan pelan Explorer. Upgrade bila anda bersedia. Tiada kontrak jangka panjang.','pricing.free_forever': 'Percuma selamanya','pricing.one_time': 'Bayar sekali','pricing.credits_day': 'kredit / hari','pricing.reset_midnight': 'Reset setiap tengah malam','pricing.valid_days': 'Sah {days} hari','pricing.per_question': '/ soalan','pricing.popular_badge': 'PALING POPULAR — PILIHAN TERBAIK','pricing.save': 'Jimat','pricing.cta_explorer': 'Cuba Percuma','pricing.cta_rintis': 'Pilih Rintis','pricing.cta_strategis': 'Pilih Strategis Sekarang','pricing.cta_prestij': 'Pilih Prestij','pricing.trust_title': 'Kenapa vendor berjaya guna TanyaLer?','pricing.faq_title': 'Soalan Lazim','pricing.bottom_cta': 'Mulakan percuma hari ini.','pricing.bottom_sub': '5 soalan percuma menunggu anda. Tiada kad kredit diperlukan.','pricing.cta_free': 'Cuba TanyaLer Percuma','pricing.footer_note': '5 soalan percuma setiap hari · Tiada komitmen · Upgrade bila bersedia','pricing.payment_note': 'Pembayaran selamat melalui FPX · SSL Dilindungi · PDPA 2010 Compliant',
    'chat.placeholder': 'Taip soalan anda tentang ePerolehan...','chat.send': 'Hantar','chat.credits_left': 'kredit berbaki','chat.welcome': 'Selamat datang ke TanyaLer','chat.welcome_sub': 'Tanya soalan tentang ePerolehan Malaysia. Saya akan jawab berdasarkan dokumen rasmi.','chat.example1': 'Apakah syarat untuk mendaftar sebagai vendor ePerolehan?','chat.example2': 'Berapa had nilai untuk sebutharga?','chat.example3': 'Apa itu TCC dan bagaimana cara memohon?','chat.thinking': 'Sedang mencari jawapan...','chat.error': 'Ralat sambungan. Sila cuba lagi.','chat.no_credits': 'Kredit habis. Sila upgrade pelan anda.','chat.upgrade': 'Upgrade Sekarang','chat.login_required': 'Sila log masuk untuk menggunakan TanyaLer.','chat.login_btn': 'Log Masuk',
    'login.title': 'Log Masuk','login.register': 'Daftar Akaun','login.google': 'Teruskan dengan Google','login.or': 'atau','login.email': 'Alamat E-mel','login.password': 'Kata Laluan','login.name': 'Nama Penuh','login.forgot': 'Lupa kata laluan?','login.submit_login': 'Log Masuk →','login.submit_register': 'Buat Akaun →','login.processing': 'Memproses...','login.terms_note': 'Dengan mendaftar, anda bersetuju dengan','login.terms': 'Terma Penggunaan','login.and': 'dan','login.privacy': 'Dasar Privasi','login.free_note': 'Tiada kad kredit diperlukan untuk daftar.','login.back': '← Kembali ke Laman Utama','login.subtitle': 'Sistem Rujukan Pintar ePerolehan Malaysia',
    'payment.success_title': 'Pembayaran Berjaya!','payment.success_sub': 'Plan {name} telah aktif. {credits} kredit dikreditkan untuk tempoh {days} hari.','payment.success_sub_generic': 'Kredit telah dikreditkan ke akaun anda.','payment.start_btn': 'Mula Guna TanyaLer','payment.back_home': 'Kembali ke Laman Utama','payment.support': 'Sokongan:','payment.failed_title': 'Pembayaran Tidak Berjaya','payment.failed_sub': 'Tiada sebarang caj dikenakan. Sila semak maklumat pembayaran anda dan cuba semula.','payment.retry': 'Cuba Semula','payment.help': 'Masalah berterusan?',
    'blog.badge': 'Blog TanyaLer','blog.title': 'Ilmu ePerolehan. Percuma untuk Anda.','blog.sub': 'Panduan praktikal, pekeliling terkini, dan strategi tender untuk vendor Malaysia yang mahu menang lebih banyak projek kerajaan.','blog.read_more': 'Baca Selanjutnya →','blog.cta_title': 'Baca artikel. Guna ilmu. Menang tender.','blog.cta_sub': 'Atau biarkan TanyaLer jawab soalan ePerolehan anda secara langsung dari 59 dokumen rasmi.','blog.cta_btn': 'Cuba TanyaLer Percuma','blog.share': 'Kongsi artikel ini','blog.related': 'Artikel Berkaitan','blog.back': '← Kembali ke Blog','blog.by': 'Oleh Pasukan TanyaLer','blog.min_read': 'min baca',
  },
  en: {
    'nav.untuk_siapa': 'Who Is It For','nav.harga': 'Pricing','nav.blog': 'Blog','nav.manual': 'Manual','nav.sokongan': 'Support','nav.log_masuk': 'Log In','nav.mula_sekarang': 'Get Started','nav.dashboard': 'Dashboard','nav.log_keluar': 'Sign Out',
    'home.badge': "Malaysia's Official ePerolehan Reference System",'home.hero_title': 'Accurate ePerolehan Answers.','home.hero_title2': 'Directly from Official Documents.','home.hero_sub': "Malaysia's first AI system that answers ePerolehan questions based on 59 official documents, 7,375 pages — not guesswork.",'home.cta_primary': 'Try Free Now','home.cta_secondary': 'View Plans & Pricing','home.free_note': '5 free questions daily · No credit card required','home.stats_docs': 'Official Documents','home.stats_pages': 'Pages','home.stats_chunks': 'Data Chunks','home.stats_accuracy': 'Accuracy',
    'pricing.badge': 'Transparent Pricing','pricing.title': 'The right plan for every need.','pricing.sub': "Start FREE with Explorer plan. Upgrade when you're ready. No long-term contracts.",'pricing.free_forever': 'Free forever','pricing.one_time': 'One-time payment','pricing.credits_day': 'credits / day','pricing.reset_midnight': 'Resets every midnight','pricing.valid_days': 'Valid for {days} days','pricing.per_question': '/ question','pricing.popular_badge': 'MOST POPULAR — BEST VALUE','pricing.save': 'Save','pricing.cta_explorer': 'Try Free','pricing.cta_rintis': 'Choose Rintis','pricing.cta_strategis': 'Choose Strategis Now','pricing.cta_prestij': 'Choose Prestij','pricing.trust_title': 'Why successful vendors use TanyaLer?','pricing.faq_title': 'Frequently Asked Questions','pricing.bottom_cta': 'Start free today.','pricing.bottom_sub': '5 free questions awaiting you. No credit card required.','pricing.cta_free': 'Try TanyaLer Free','pricing.footer_note': '5 free questions daily · No commitment · Upgrade when ready','pricing.payment_note': 'Secure payment via FPX · SSL Protected · PDPA 2010 Compliant',
    'chat.placeholder': 'Type your ePerolehan question here...','chat.send': 'Send','chat.credits_left': 'credits remaining','chat.welcome': 'Welcome to TanyaLer','chat.welcome_sub': "Ask questions about Malaysian ePerolehan. I'll answer based on official documents.",'chat.example1': 'What are the requirements to register as an ePerolehan vendor?','chat.example2': 'What is the value limit for sebutharga?','chat.example3': 'What is TCC and how do I apply for it?','chat.thinking': 'Searching for answer...','chat.error': 'Connection error. Please try again.','chat.no_credits': 'Credits exhausted. Please upgrade your plan.','chat.upgrade': 'Upgrade Now','chat.login_required': 'Please log in to use TanyaLer.','chat.login_btn': 'Log In',
    'login.title': 'Log In','login.register': 'Create Account','login.google': 'Continue with Google','login.or': 'or','login.email': 'Email Address','login.password': 'Password','login.name': 'Full Name','login.forgot': 'Forgot password?','login.submit_login': 'Log In →','login.submit_register': 'Create Account →','login.processing': 'Processing...','login.terms_note': 'By registering, you agree to our','login.terms': 'Terms of Use','login.and': 'and','login.privacy': 'Privacy Policy','login.free_note': 'No credit card required to register.','login.back': '← Back to Home','login.subtitle': "Malaysia's Smart ePerolehan Reference System",
    'payment.success_title': 'Payment Successful!','payment.success_sub': '{name} plan is now active. {credits} credits added for {days} days.','payment.success_sub_generic': 'Credits have been added to your account.','payment.start_btn': 'Start Using TanyaLer','payment.back_home': 'Back to Home','payment.support': 'Support:','payment.failed_title': 'Payment Unsuccessful','payment.failed_sub': 'No charges were made. Please check your payment details and try again.','payment.retry': 'Try Again','payment.help': 'Still having issues?',
    'blog.badge': 'TanyaLer Blog','blog.title': 'ePerolehan Knowledge. Free for You.','blog.sub': 'Practical guides, latest circulars, and tender strategies for Malaysian vendors who want to win more government projects.','blog.read_more': 'Read More →','blog.cta_title': 'Read. Learn. Win tenders.','blog.cta_sub': 'Or let TanyaLer answer your ePerolehan questions directly from 59 official documents.','blog.cta_btn': 'Try TanyaLer Free','blog.share': 'Share this article','blog.related': 'Related Articles','blog.back': '← Back to Blog','blog.by': 'By TanyaLer Team','blog.min_read': 'min read',
  },
  zh: {
    'nav.untuk_siapa': '适用对象','nav.harga': '价格','nav.blog': '博客','nav.manual': '使用手册','nav.sokongan': '客户支持','nav.log_masuk': '登录','nav.mula_sekarang': '立即开始','nav.dashboard': '控制台','nav.log_keluar': '登出',
    'home.badge': '马来西亚官方电子采购参考系统','home.hero_title': '精准的电子采购解答。','home.hero_title2': '直接来自官方文件。','home.hero_sub': '马来西亚首个基于59份官方文件、7,375页内容回答电子采购问题的AI系统——不是猜测。','home.cta_primary': '立即免费试用','home.cta_secondary': '查看计划与价格','home.free_note': '每天5个免费问题 · 无需信用卡','home.stats_docs': '官方文件','home.stats_pages': '页数','home.stats_chunks': '数据块','home.stats_accuracy': '准确率',
    'pricing.badge': '透明定价','pricing.title': '适合每种需求的方案。','pricing.sub': '从免费的Explorer计划开始。随时升级。无需长期合约。','pricing.free_forever': '永久免费','pricing.one_time': '一次性付款','pricing.credits_day': '积分 / 天','pricing.reset_midnight': '每天午夜重置','pricing.valid_days': '有效期 {days} 天','pricing.per_question': '/ 问题','pricing.popular_badge': '最受欢迎 — 最佳选择','pricing.save': '节省','pricing.cta_explorer': '免费试用','pricing.cta_rintis': '选择 Rintis','pricing.cta_strategis': '立即选择 Strategis','pricing.cta_prestij': '选择 Prestij','pricing.trust_title': '为什么成功的供应商使用 TanyaLer？','pricing.faq_title': '常见问题','pricing.bottom_cta': '今天就免费开始。','pricing.bottom_sub': '5个免费问题等待您。无需信用卡。','pricing.cta_free': '免费试用 TanyaLer','pricing.footer_note': '每天5个免费问题 · 无承诺 · 随时升级','pricing.payment_note': '通过FPX安全付款 · SSL保护 · PDPA 2010合规',
    'chat.placeholder': '在此输入您的电子采购问题...','chat.send': '发送','chat.credits_left': '积分剩余','chat.welcome': '欢迎使用 TanyaLer','chat.welcome_sub': '询问有关马来西亚电子采购的问题。我将根据官方文件回答。','chat.example1': '注册电子采购供应商的条件是什么？','chat.example2': '报价的价值限额是多少？','chat.example3': '什么是TCC，如何申请？','chat.thinking': '正在搜索答案...','chat.error': '连接错误，请重试。','chat.no_credits': '积分已用完。请升级您的计划。','chat.upgrade': '立即升级','chat.login_required': '请登录以使用 TanyaLer。','chat.login_btn': '登录',
    'login.title': '登录','login.register': '注册账户','login.google': '使用Google继续','login.or': '或','login.email': '电子邮件地址','login.password': '密码','login.name': '全名','login.forgot': '忘记密码？','login.submit_login': '登录 →','login.submit_register': '创建账户 →','login.processing': '处理中...','login.terms_note': '注册即表示您同意我们的','login.terms': '使用条款','login.and': '和','login.privacy': '隐私政策','login.free_note': '注册无需信用卡。','login.back': '← 返回首页','login.subtitle': '马来西亚智能电子采购参考系统',
    'payment.success_title': '付款成功！','payment.success_sub': '{name} 计划已激活。{credits} 积分已添加，有效期 {days} 天。','payment.success_sub_generic': '积分已添加到您的账户。','payment.start_btn': '开始使用 TanyaLer','payment.back_home': '返回首页','payment.support': '技术支持：','payment.failed_title': '付款未成功','payment.failed_sub': '未收取任何费用。请检查您的付款信息并重试。','payment.retry': '重试','payment.help': '仍有问题？',
    'blog.badge': 'TanyaLer 博客','blog.title': '电子采购知识。免费为您提供。','blog.sub': '为希望赢得更多政府项目的马来西亚供应商提供实用指南、最新通告和投标策略。','blog.read_more': '阅读更多 →','blog.cta_title': '阅读文章。运用知识。赢得投标。','blog.cta_sub': '或让 TanyaLer 直接从59份官方文件中回答您的电子采购问题。','blog.cta_btn': '免费试用 TanyaLer','blog.share': '分享这篇文章','blog.related': '相关文章','blog.back': '← 返回博客','blog.by': '作者：TanyaLer 团队','blog.min_read': '分钟阅读',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>('ms');
  useEffect(() => {
    const saved = localStorage.getItem('tanyaler_lang') as Language;
    if (saved && ['ms', 'en', 'zh'].includes(saved)) setLangState(saved);
  }, []);
  const setLang = (newLang: Language) => { setLangState(newLang); localStorage.setItem('tanyaler_lang', newLang); };
  const t = (key: string): string => translations[lang][key] || translations['ms'][key] || key;
  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }
